"""
Signal 1: LLM-based scoring via Groq API.

Asks llama-3.3-70b-versatile to reason through writing features before
returning a score in [0.0, 1.0]:
  0.0 = high confidence human-written
  1.0 = high confidence AI-generated

Test independently before wiring into app.py:
    python signals/llm_signal.py
"""

import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

SYSTEM_PROMPT = """You are an AI-detection classifier. Assess whether the text was written by a human or generated by an AI.

Step 1 — briefly note what you observe about each of these:
- Sentence length uniformity (AI tends to be very consistent)
- Formulaic transitions ("Furthermore", "It is important to note")
- Hedging language ("it is worth noting", "one might argue")
- Unpolished markers: typos, run-ons, informal tone, tangential asides (human)
- IMPORTANT: Do not use genre as a signal. Poetry, essays, and notes can all be AI or human.

Step 2 — output your score on the LAST line in exactly this format:
SCORE: 0.00

Scale: 0.0 = very confident human, 1.0 = very confident AI.

Note: You can output any score between 0.0 and 1.0, not just those two numbers."""


def get_llm_score(text: str) -> float:
    """
    Returns a float in [0.0, 1.0] representing the LLM's confidence
    that the given text is AI-generated.

    Raises ValueError if the model returns something unparseable.
    """
    response = _client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        max_tokens=300,
        temperature=0.0,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )

    raw = response.choices[0].message.content.strip()

    # parse the last "SCORE: x.xx" line from the chain-of-thought response
    score_line = None
    for line in reversed(raw.splitlines()):
        if line.strip().upper().startswith("SCORE:"):
            score_line = line.split(":", 1)[1].strip()
            break

    if score_line is None:
        raise ValueError(f"No SCORE: line found in response:\n{raw}")

    try:
        score = float(score_line)
    except ValueError:
        raise ValueError(f"Unparseable score value: {repr(score_line)}")

    return max(0.0, min(1.0, score))


# ── manual test ───────────────────────────────────────────────────────────────
if __name__ == "__main__":
    samples = [
        (
            "Gemini generated poem",
            """A cold ceramic mug against my palm,
The radiator hums its heavy tune,
And for a second, everything is calm,
Beneath the pale, indifferent afternoon.

I think of lines I meant to write last week,
Of keys I lost, and words I shouldn't say,
The quiet, stubborn ways we try to speak
Across the gaps we widen day by day.""",
        ),
        (
            "human - William Faulkner poem",
            """The race's splendor lifts her lip, exposes
Amid her scarlet smile her little teeth;
The years are sand the wind plays with; beneath
The prisoned music of her deathless roses.

Within frostbitten rock she's fixed and glassed;
Now man may look upon her without fear.
But her contemptuous eyes back through him stare
And shear his fatuous sheep when he has passed.""",
        ),
        (
            "AI with human edits",
            "Additionally, Athens' religious practices and devotion are symbolized "
            "by the Parthenon. Athena's temple reflected ideals relevant to a variety "
            "of Greeks, despite being their patron goddess. Some of these ideals "
            "included wisdom, protection, and civic strength. Despite being a subject, "
            "I still felt a sense of shared reverence every time I saw the Parthenon.",
        ),
        (
            "human - personal notes",
            "- Found this book through @lifeonbooks instagram\n"
            "- Plot: The crazy events of a well-known family's anniversary party, "
            "with the father a prominent magistrate in Bogota, Colombia\n"
            "- Overall, a book that kept you on your toes",
        ),
        # Provided Examples
        (
            "Clearly AI-generated (should score high)",
            """Artificial intelligence represents a transformative paradigm shift in modern society. 
It is important to note that while the benefits of AI are numerous, it is equally 
essential to consider the ethical implications. Furthermore, stakeholders across 
various sectors must collaborate to ensure responsible deployment."""
        ),
        (
            "Clearly human-written (should score low)",
            """ok so i finally tried that new ramen place downtown and honestly? 
underwhelming. the broth was fine but they put WAY too much sodium in it and 
i was thirsty for like three hours after. my friend got the spicy version and 
said it was better. probably won't go back unless someone drags me there"""
        ),
        (
            "Borderline: formal human writing (may score mid-high on stylometrics)",
            """The relationship between monetary policy and asset price inflation has been 
extensively studied in the literature. Central banks face a fundamental tension 
between their mandate for price stability and the unintended consequences of 
prolonged low interest rates on equity and real estate valuations."""
        ),
        (
            "Borderline: lightly edited AI output (should ideally score mid-range)",
            """I've been thinking a lot about remote work lately. There are genuine tradeoffs — 
flexibility and no commute on one side, isolation and blurred work-life boundaries 
on the other. Studies show productivity varies widely by individual and role type."""
        )
    ]

    print(f"{'Label':<35} {'Score':>6}  Verdict")
    print("-" * 55)
    for label, text in samples:
        score = get_llm_score(text)
        verdict = "AI  " if score >= 0.70 else ("????" if score >= 0.40 else "HUM ")
        print(f"{label:<35} {score:>6.3f}  {verdict}")